#:kivy 1.0.9

<GeneSeek>:

    BoxLayout:
        orientation: 'vertical'
        padding: 20
        fullscreen: True    
        width: root.width
        height: root.height

        BoxLayout:
            size_hint: 0.8,0.1
            orientation: 'horizontal'
            padding: 20
            
            Label:
                text: "Gene Symbol"

            TextInput:
                id: textinput
                multiline: False
                focus: True
                on_text_validate: root.seek_summary()

            Button:
                text: 'Get Summary'
                on_release: root.seek_summary()

        RstDocument:
            id: ficha

